/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CocosIndexRouteImport } from './routes/cocos/index'
import { Route as ComandosIndexRouteImport } from './routes/comandos/index'
import { Route as TestDatasIndexRouteImport } from './routes/test-datas/index'
import { Route as WIdIndexRouteImport } from './routes/w.$id.index'
import { Route as WIdEEntityIdRouteImport } from './routes/w.$id.e.$entityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CocosIndexRoute = CocosIndexRouteImport.update({
  id: '/cocos/',
  path: '/cocos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandosIndexRoute = ComandosIndexRouteImport.update({
  id: '/comandos/',
  path: '/comandos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDatasIndexRoute = TestDatasIndexRouteImport.update({
  id: '/test-datas/',
  path: '/test-datas/',
  getParentRoute: () => rootRouteImport,
} as any)
const WIdIndexRoute = WIdIndexRouteImport.update({
  id: '/w/$id/',
  path: '/w/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WIdEEntityIdRoute = WIdEEntityIdRouteImport.update({
  id: '/w/$id/e/$entityId',
  path: '/w/$id/e/$entityId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cocos/': typeof CocosIndexRoute
  '/comandos/': typeof ComandosIndexRoute
  '/test-datas/': typeof TestDatasIndexRoute
  '/w/$id/': typeof WIdIndexRoute
  '/w/$id/e/$entityId': typeof WIdEEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cocos': typeof CocosIndexRoute
  '/comandos': typeof ComandosIndexRoute
  '/test-datas': typeof TestDatasIndexRoute
  '/w/$id': typeof WIdIndexRoute
  '/w/$id/e/$entityId': typeof WIdEEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cocos/': typeof CocosIndexRoute
  '/comandos/': typeof ComandosIndexRoute
  '/test-datas/': typeof TestDatasIndexRoute
  '/w/$id/': typeof WIdIndexRoute
  '/w/$id/e/$entityId': typeof WIdEEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cocos/'
    | '/comandos/'
    | '/test-datas/'
    | '/w/$id/'
    | '/w/$id/e/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cocos'
    | '/comandos'
    | '/test-datas'
    | '/w/$id'
    | '/w/$id/e/$entityId'
  id:
    | '__root__'
    | '/'
    | '/cocos/'
    | '/comandos/'
    | '/test-datas/'
    | '/w/$id/'
    | '/w/$id/e/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CocosIndexRoute: typeof CocosIndexRoute
  ComandosIndexRoute: typeof ComandosIndexRoute
  TestDatasIndexRoute: typeof TestDatasIndexRoute
  WIdIndexRoute: typeof WIdIndexRoute
  WIdEEntityIdRoute: typeof WIdEEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocos/': {
      id: '/cocos/'
      path: '/cocos'
      fullPath: '/cocos/'
      preLoaderRoute: typeof CocosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comandos/': {
      id: '/comandos/'
      path: '/comandos'
      fullPath: '/comandos/'
      preLoaderRoute: typeof ComandosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-datas/': {
      id: '/test-datas/'
      path: '/test-datas'
      fullPath: '/test-datas/'
      preLoaderRoute: typeof TestDatasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$id/': {
      id: '/w/$id/'
      path: '/w/$id'
      fullPath: '/w/$id/'
      preLoaderRoute: typeof WIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$id/e/$entityId': {
      id: '/w/$id/e/$entityId'
      path: '/w/$id/e/$entityId'
      fullPath: '/w/$id/e/$entityId'
      preLoaderRoute: typeof WIdEEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CocosIndexRoute: CocosIndexRoute,
  ComandosIndexRoute: ComandosIndexRoute,
  TestDatasIndexRoute: TestDatasIndexRoute,
  WIdIndexRoute: WIdIndexRoute,
  WIdEEntityIdRoute: WIdEEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
