/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CocosRouteImport } from './routes/cocos'
import { Route as ComandosRouteImport } from './routes/comandos'
import { Route as TestDatasRouteImport } from './routes/test-datas'
import { Route as WIdRouteImport } from './routes/w.$id'
import { Route as WIdEEntityIdRouteImport } from './routes/w.$id.e.$entityId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CocosRoute = CocosRouteImport.update({
  id: '/cocos',
  path: '/cocos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComandosRoute = ComandosRouteImport.update({
  id: '/comandos',
  path: '/comandos',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDatasRoute = TestDatasRouteImport.update({
  id: '/test-datas',
  path: '/test-datas',
  getParentRoute: () => rootRouteImport,
} as any)
const WIdRoute = WIdRouteImport.update({
  id: '/w/$id',
  path: '/w/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WIdEEntityIdRoute = WIdEEntityIdRouteImport.update({
  id: '/e/$entityId',
  path: '/e/$entityId',
  getParentRoute: () => WIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cocos': typeof CocosRoute
  '/comandos': typeof ComandosRoute
  '/test-datas': typeof TestDatasRoute
  '/w/$id': typeof WIdRouteWithChildren
  '/w/$id/e/$entityId': typeof WIdEEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cocos': typeof CocosRoute
  '/comandos': typeof ComandosRoute
  '/test-datas': typeof TestDatasRoute
  '/w/$id': typeof WIdRouteWithChildren
  '/w/$id/e/$entityId': typeof WIdEEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cocos': typeof CocosRoute
  '/comandos': typeof ComandosRoute
  '/test-datas': typeof TestDatasRoute
  '/w/$id': typeof WIdRouteWithChildren
  '/w/$id/e/$entityId': typeof WIdEEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cocos'
    | '/comandos'
    | '/test-datas'
    | '/w/$id'
    | '/w/$id/e/$entityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cocos'
    | '/comandos'
    | '/test-datas'
    | '/w/$id'
    | '/w/$id/e/$entityId'
  id:
    | '__root__'
    | '/'
    | '/cocos'
    | '/comandos'
    | '/test-datas'
    | '/w/$id'
    | '/w/$id/e/$entityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CocosRoute: typeof CocosRoute
  ComandosRoute: typeof ComandosRoute
  TestDatasRoute: typeof TestDatasRoute
  WIdRoute: typeof WIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocos': {
      id: '/cocos'
      path: '/cocos'
      fullPath: '/cocos'
      preLoaderRoute: typeof CocosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comandos': {
      id: '/comandos'
      path: '/comandos'
      fullPath: '/comandos'
      preLoaderRoute: typeof ComandosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-datas': {
      id: '/test-datas'
      path: '/test-datas'
      fullPath: '/test-datas'
      preLoaderRoute: typeof TestDatasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$id': {
      id: '/w/$id'
      path: '/w/$id'
      fullPath: '/w/$id'
      preLoaderRoute: typeof WIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$id/e/$entityId': {
      id: '/w/$id/e/$entityId'
      path: '/e/$entityId'
      fullPath: '/w/$id/e/$entityId'
      preLoaderRoute: typeof WIdEEntityIdRouteImport
      parentRoute: typeof WIdRoute
    }
  }
}

interface WIdRouteChildren {
  WIdEEntityIdRoute: typeof WIdEEntityIdRoute
}

const WIdRouteChildren: WIdRouteChildren = {
  WIdEEntityIdRoute: WIdEEntityIdRoute,
}

const WIdRouteWithChildren = WIdRoute._addFileChildren(WIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CocosRoute: CocosRoute,
  ComandosRoute: ComandosRoute,
  TestDatasRoute: TestDatasRoute,
  WIdRoute: WIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
